sudo: false
language: python
python:
- '3.6'
install:
- python -m pip install setuptools twine
- python -m pip install .[test]
- python -m pip install .[async]
- python -m pip install .[sync]
- python -m pip install attrs==17.4.0
script: pytest
deploy:
  provider: pypi
  user: chrispruitt
  distributions: sdist bdist_wheel
  skip_existing: true
  password: ${PYPI_PASS}
  on:
    tags: true
    branch: master
